name: Build and Test

on: [push, pull_request]

jobs:
  build:
    # Use the standard gitea.com shared runner environment.
    runs-on: ubuntu-latest

    # Environment variables remain the same.
    env:
      CFLAGS: -pthread -Wno-unused-result -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -mtune=generic -D_GNU_SOURCE -fwrapv

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clone m2crypto source
        run: git clone https://git.sr.ht/~mcepl/m2crypto

      # Install dependencies using Ubuntu's 'apt-get' instead of Fedora's 'dnf'.
      # Package names have been translated (e.g., python3-devel -> python3-dev).
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y swig python3 python3-dev python3-pip libssl-dev openssl python3-setuptools python3-twisted python3-pexpect python3-docutils python3-mypy

      - name: Build wheel
        working-directory: ./m2crypto
        run: |
          export PATH=$PATH:$HOME/.local/bin
          python3 -mpip install --user -r dev-requirements.txt
          python3 -mpip wheel --verbose --no-cache-dir --no-clean --no-build-isolation --wheel-dir dist/ --editable .
          find . -name \*.c
          find . -name \*.whl -o -name \*.tar.gz
          mkdir -p shadowing/sys && touch shadowing/sys/types.h
          # Dynamically determine the build path for PYTHONPATH
          export PYTHONPATH_DYNAMIC=$(readlink -f build/lib.*)
          # We no longer export this to GITEA_ENV to improve compatibility.
          python3 -mpip install -v --upgrade --target ${PYTHONPATH_DYNAMIC} --no-compile --ignore-installed --no-deps --no-index dist/[mM]2[cC]rypto*.whl

      - name: Run mypy check
        working-directory: ./m2crypto
        run: |
          # Recalculate PYTHONPATH directly in this step.
          PYTHONPATH=$(readlink -f build/lib.*) python3 -mmypy --no-color-output src/M2Crypto

      - name: Run unittests
        working-directory: ./m2crypto
        run: |
          # Recalculate PYTHONPATH directly in this step.
          PYTHONPATH=$(readlink -f build/lib.*) python3 -munittest -b -v tests.alltests.suite
          echo "Test task finished."

      - name: Validate README
        working-directory: ./m2crypto
        run: |
          echo "Current ref: ${{ gitea.ref_name }}"
          python3 -mdocutils --strict README.rst >/dev/null
          # The README update logic remains commented out as it is platform-specific.
          if [[ "${{ gitea.ref_name }}" == "master" ]]; then
            echo "On master branch. Skipping Sourcehut-specific 'hut' command."
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            m2crypto/src/SWIG/_m2crypto_wrap.c
            m2crypto/dist/*.whl
            m2crypto/dist/*.tar.gz
